### ISSUE TITLE
关于tar2json协议的设计的疑问

### ISSUE THREAD

**Issue by wangxi761** [TarsCloud/TarsJMeter#10]
为什么不能做直接的转换，用jce+json（http那种）映射，而是要一个比较复杂的json嵌套（虽然可以省掉jce文件的读入）

毕竟需要tars2json转换的时候，还是需要jce文件

**Comment by boycs007** [comment]
这么做是为了在测试时，比较方便的修改数据。IDL描述语言里面，是没有数据定义的。使用一次tars2json之后，后续可以用这一个json生成N份数据变种，让tester 对Tars数据可读、可写、可参数化，且无需懂代码。
