### ISSUE TITLE
sample not tars request

### ISSUE THREAD

**Issue by guwenwenhappy** [TarsCloud/TarsJMeter#2]
JDK:14
Jmeter:5.3
tarsJmeter.jar copy lib/ext

start jmeter.sh  sampler not tars request

**Comment by boycs007** [comment]
You closed the issue, is there any problem?

**Comment by guwenwenhappy** [comment]
error Operation，
1 .Direct click jmeter.sh ,sampler not tars request 
2.command line start jmeter.sh ,sampler has tars request
